const DATA={"wax": {"title": "ขี้ผึ้ง", "num": "2.1", "icon": "🕯️", "items": [["การศึกษาประสิทธิผลของการใช้ขี้ผึ้งตำรับ ‘เสว่ฟู่จู๋ยวี’ ในการรักษาภาวะปวดชนิดเลือดคั่งตามศาสตร์การแพทย์แผนจีนในผู้สูงอายุ", "Huachiew Archiving System", "https://has.hcu.ac.th/jspui/handle/123456789/1938", "เปิดแหล่งข้อมูล"], ["การประเมินคุณภาพของขี้ผึ้งไทยเสริมสมุนไพร", "University of the Thai Chamber of Commerce", "https://scholar.utcc.ac.th/server/api/core/bitstreams/875bc3d3-0252-4832-a713-95a497e6608d/content", "เปิด PDF"], ["การศึกษาประสิทธิผลของการใช้ขี้ผึ้งตำรับ ‘เสว่ฟู่จู๋ยวี’ — ฉบับ PDF", "Huachiew Archiving System", "https://has.hcu.ac.th/jspui/bitstream/123456789/1938/1/Worapong-Paduka.pdf", "เปิด PDF"], ["การสร้างมูลค่าเพิ่มในผลิตภัณฑ์ครีมบำรุงผิวจากขี้ผึ้งและไขมะพร้าวรูปครีมสติ๊ก", "วารสารมนุษยศาสตร์และสังคมศาสตร์ มหาวิทยาลัยเอเชียอาคเนย์", "https://so05.tci-thaijo.org/index.php/saujournalssh/article/view/264892", "เปิดบทความ"], ["ประสิทธิภาพของแผ่นขี้ผึ้งปิดแผลเคลือบยาคลอร์เฮกซิดีนอะซีเตตต่อการป้องกันการติดเชื้อแบคทีเรีย", "HITAP", "https://db.hitap.net/articles/3394", "เปิดบทความ"]]}, "petrolatum": {"title": "ปิโตรเลียมเจลลี่", "num": "2.2", "icon": "🫙", "items": [["Petrolatum in Skincare: Friend or Foe for Your Skin Health?", "Clinikally", "https://www.clinikally.com/blogs/news/petrolatum-in-skincare-friend-or-foe-for-your-skin-barrier", "เปิดบทความ"], ["4 เหตุผล..ผู้หญิงพึงระวัง สวยด้วย ‘ปิโตรเลียมเจลลี่’", "ไทยโพสต์", "https://www.thaipost.net/main/detail/1017", "เปิดบทความ"], ["จุลินทรีย์กับความสามารถในการเพิ่มผลผลิตปิโตรเลียม", "มหาวิทยาลัยเชียงใหม่", "https://www.cmu.ac.th/th/article/e214b6e4-7770-4cf8-bd17-7d5e2c5283c9", "เปิดบทความ"], ["บริษัท ปตท.สำรวจและผลิตปิโตรเลียม จำกัด (มหาชน)", "MTEC / NSTDA", "https://www.mtec.or.th/stakeholders-perspective-pttep/", "เปิดบทความ"], ["เจาะลึก ‘ปิโตรเลียมเจล’ กับประโยชน์ด้านความงามสุดอเนกประสงค์", "Vogue Thailand", "https://vogue.co.th/beauty/article/petroleum-jelly", "เปิดบทความ"]]}, "coconut": {"title": "น้ำมันมะพร้าว", "num": "2.3", "icon": "🥥", "items": [["ผลของการบริโภคน้ำมันมะพร้าวต่อไขมันในเลือด", "วารสารมหาวิทยาลัยคริสเตียน", "https://he01.tci-thaijo.org/index.php/CUTJ/article/view/155269", "เปิดบทความ"], ["ผลระยะสั้นของน้ำมันมะพร้าวสกัดเย็นต่อระดับไขมันในเลือดในผู้ป่วยที่ได้รับยาลดไขมันกลุ่มสเตติน", "Thai JPEN", "https://he02.tci-thaijo.org/index.php/ThaiJPEN/article/view/242057", "เปิดบทความ"], ["น้ำมันมะพร้าว (Coconut Oil) บำรุงผมและผิว รักษาแผล ให้ความชุ่มชื้น", "CosmeHerb / หน่วยงานภาครัฐ", "https://cosmeherb.nbt.or.th/herb_recommend/detail/7", "เปิดข้อมูล"], ["การยับยั้งอนุมูลอิสระและเอนไซม์เมทริกซ์เมทัลโลโปรติเนสของน้ำมันมะพร้าวบริสุทธิ์ และผลิตภัณฑ์ลดการอักเสบ", "วารสารวิจัยและส่งเสริมวิชาการเกษตร", "https://li01.tci-thaijo.org/index.php/MJUJN/article/view/214341", "เปิดบทความ"], ["เอกสารงานวิจัย: Enzymatic methods", "ARDA", "https://cads.arda.or.th/th/documents/research/dc852f8e-2d0c-4dda-9c1b-6da47e7216ab_th-TH?q=Enzymatic%20methods", "เปิดเอกสาร"]]}};
const root=document.getElementById('categories'), search=document.getElementById('search'), clear=document.getElementById('clear'), empty=document.getElementById('empty');
let filter='all', term='';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function render(){
 root.innerHTML=''; let total=0;
 Object.entries(DATA).forEach(([key,cat])=>{
  if(filter!=='all'&&filter!==key)return;
  const items=cat.items.filter(x=>!term||(`${x[0]} ${x[1]} ${cat.title}`).toLocaleLowerCase('th').includes(term));
  if(!items.length)return; total+=items.length;
  const sec=document.createElement('section');sec.className='category';
  sec.innerHTML=`<div class="cat-head"><div class="cat-icon">${cat.icon}</div><div><p>หมวด ${cat.num}</p><h3>${esc(cat.title)}</h3></div><span class="count">${items.length} แหล่งข้อมูล</span></div><div class="cards">${items.map((x,i)=>`<article class="card"><div class="num">${i+1}</div><h4>${esc(x[0])}</h4><p class="source"><b>แหล่งข้อมูล:</b> ${esc(x[1])}</p><div class="actions"><a class="open" href="${esc(x[2])}" target="_blank" rel="noopener noreferrer">${esc(x[3])} ↗</a><button class="copy" data-url="${esc(x[2])}" title="คัดลอกลิงก์">⧉</button></div></article>`).join('')}</div>`;
  root.appendChild(sec);
 });
 empty.hidden=total!==0;
}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
search.oninput=e=>{term=e.target.value.trim().toLocaleLowerCase('th');clear.style.display=term?'block':'none';render()};
clear.onclick=()=>{search.value='';term='';clear.style.display='none';search.focus();render()};
const toast=document.getElementById('toast');let timer;
document.addEventListener('click',async e=>{const b=e.target.closest('.copy');if(!b)return;try{await navigator.clipboard.writeText(b.dataset.url)}catch{const t=document.createElement('textarea');t.value=b.dataset.url;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),1800)});
const top=document.getElementById('top');addEventListener('scroll',()=>top.classList.toggle('show',scrollY>450),{passive:true});top.onclick=()=>scrollTo({top:0,behavior:'smooth'});render();
